version: '3.8'
networks:
  monitoring:
    driver: bridge
volumes:
    mysql-data:
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    networks:
      - monitoring
    volumes:
      - .:/app
    depends_on:
      - mysql-server
      - redis

  mysql-server:
    image: mysql:8.0

    restart: always

    environment:
      - MYSQL_DATABASE=cass
      - MYSQL_ROOT_PASSWORD=1234
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  redis:
    image: redis:latest
    command: [ "redis-server", "--bind", "redis", "--port", "6379" ]
    container_name: redis
    ports:
      - "6379:6379"
    restart: always

